package:
  name: ties_md
  version: 0.0.0
  license: 'LGPL'

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python {{ python }} # [not ppc64le]
    - python 3.7.3 # [ppc64le]
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - netcdf4
    - libnetcdf
    - pyyaml
    - numba
    - docopt
    - multiprocess
    - openmm
    - cython
    - ties_ana
    - mpiplus
    - openmmtools # [not ppc64le]

about:
  home: https://github.com/UCL-CCS/TIES_MD
