package:
  name: ties_md
  version: 0.0.0
  license: 'LGPL'

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - netcdf4
    - libnetcdf
    - pyyaml
    - numba
    - docopt
    - multiprocess
    - cython
    - mpiplus
    - scikit-learn
    - six
    - openmm # [not ppc64le]
    - pymbar >= 4.0.1 # [not ppc64le]
    - openmmtools # [not ppc64le]

about:
  home: https://github.com/UCL-CCS/TIES_MD
