name: publish_conda

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]

    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: maxibor/conda-package-publish-action@v1.1
      with:
        subDir: devtools/conda-recipe
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}

